version: '3.7'

services:
  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile
    image: grpc-sandbox/laravel
    volumes:
      - ./laravel:/var/www/app/
    ports:
      - 8000:8000
    command: php artisan serve --host 0.0.0.0

  rails:
    build: 
      context: ./rails
      dockerfile: Dockerfile
    image: grpc-sandbox/rails
    volumes:
    volumes:
      - ./rails:/rails
    ports:
      - 3000:3000
    command: rails c -b 0.0.0.0
