# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: person.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("person.proto", :syntax => :proto3) do
    add_message "persion.PersionRequest" do
      optional :id, :int32, 1
    end
    add_message "persion.PersonResponse" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :gender, :enum, 3, "persion.PersonResponse.Gender"
    end
    add_enum "persion.PersonResponse.Gender" do
      value :MAN, 0
      value :WOMAN, 1
    end
  end
end

module Persion
  PersionRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persion.PersionRequest").msgclass
  PersonResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persion.PersonResponse").msgclass
  PersonResponse::Gender = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("persion.PersonResponse.Gender").enummodule
end
